Handle errors from concurrent process death
My hope is that this will fix test flakiness like was seen in
https://github.com/Springtail-inc/springtail/actions/runs/13185730949/job/36807221811?pr=272

```
Starting replication on database instance...
Checking log path /opt/springtail/logs is writable...
2025-02-06 19:00:14,769 - DEBUG - Connecting to database: springtail with username: springtail and host: localhost
2025-02-06 19:00:14,783 - DEBUG - Executing sql: CREATE PUBLICATION "springtail_pub" FOR ALL TABLES; with args: None
2025-02-06 19:00:14,785 - DEBUG - Executing sql: SELECT pg_create_logical_replication_slot(%s, 'pgoutput'); with args: springtail_slot
2025-02-06 19:00:14,809 - DEBUG - Executing sql script: ../../scripts/triggers.sql

Starting daemons...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 497, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 495, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1777, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 840, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 828, in cat
    with _open(fname) as f:
         ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 788, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/proc/8427/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/springtail/springtail/python/testing/test_runner.py", line 219, in <module>
    success = test.run()
              ^^^^^^^^^^
  File "/__w/springtail/springtail/python/testing/test_set.py", line 121, in run
    springtail.start(self._config_file, self._build_dir, do_cleanup=False)
  File "/__w/springtail/springtail/python/testing/springtail.py", line 483, in start
    start_daemons(build_dir, CORE_DAEMONS)
  File "/__w/springtail/springtail/python/shared/sysutils.py", line 146, in start_daemons
    if check_daemons_running(daemon_names)[0]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/springtail/springtail/python/shared/sysutils.py", line 51, in check_daemons_running
    (pids, not_running) = running_pids(daemons)
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/__w/springtail/springtail/python/shared/common.py", line 82, in running_pids
    if proc.status() != psutil.STATUS_ZOMBIE and proc.info['name'] in names:
       ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 724, in status
    return self._proc.status()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 2284, in status
    letter = self._parse_stat_file()['status']
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1723, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=8427, name='postgres')
```